disabled_rules:
  - multiple_closures_with_trailing_closure
  - empty_parentheses_with_trailing_closure
  - identifier_name
  - unused_optional_binding
  - line_length
  - function_parameter_count
  - syntactic_sugar
  - implicit_getter
  - todo
  - weak_delegate
  - cyclomatic_complexity
  - void_return
  - legacy_hashing
  - type_name
  - function_body_length

excluded:
  - BabylonTests
  - Pods
# configurable rules
# eventually removing those to abide by the default values would be nice.
# Just being more lenient for the moment
file_length:
  warning: 1000
  error: 1200

force_cast: error

type_body_length:
  warning: 300
  error: 500

# this one is a keeper, maybe we could trim down max_lengths but this should stay in the .swiftlint.yml file
type_name:
  min_length:
    error: 3 # only error
  max_length:
    warning: 50
    error: 65
  excluded: # excluded via string array
    - T
